"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-24 18:14:19.900446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('store_number', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('hostname', sa.String(length=253), nullable=False),
    sa.Column('host', sa.String(length=253), nullable=False),
    sa.Column('ftp_port', sa.Integer(), nullable=False),
    sa.Column('login_home', sa.String(length=500), nullable=False),
    sa.Column('config_video_path', sa.String(length=500), nullable=True),
    sa.Column('video_path', sa.String(length=500), nullable=True),
    sa.Column('video_path_source', sa.String(length=20), nullable=True),
    sa.Column('video_path_confirmed_by', sa.String(length=254), nullable=True),
    sa.Column('video_path_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('max_bytes', sa.BigInteger(), nullable=True),
    sa.Column('in_config', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ftp_banner', sa.String(length=200), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_reconcile_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(), nullable=True),
    sa.Column('staging_exists', sa.Boolean(), nullable=False),
    sa.Column('discovery', sa.JSON(), nullable=True),
    sa.Column('discovery_at', sa.DateTime(), nullable=True),
    sa.Column('plan_digest', sa.String(length=64), nullable=True),
    sa.Column('lock_owner', sa.String(length=100), nullable=True),
    sa.Column('lock_expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices')),
    sa.UniqueConstraint('code', name=op.f('uq_devices_code')),
    sa.UniqueConstraint('store_number', name=op.f('uq_devices_store_number'))
    )
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('in_config', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_groups')),
    sa.UniqueConstraint('name', name=op.f('uq_groups_name'))
    )
    op.create_table('system_state',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_system_state'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('authorized', sa.Boolean(), nullable=False),
    sa.Column('authorized_by', sa.String(length=254), nullable=True),
    sa.Column('authorized_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=40), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('original_path', sa.String(length=500), nullable=True),
    sa.Column('media_path', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=500), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('source_info', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('origin_detail', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.String(length=254), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('processing', 'ready', 'failed')", name=op.f('ck_videos_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_videos'))
    )
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_videos_sha256'), ['sha256'], unique=False)

    op.create_table('assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=10), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_fallback', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_by', sa.String(length=254), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=254), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("(target_type = 'all' AND target_id IS NULL) OR (target_type != 'all' AND target_id IS NOT NULL)", name=op.f('ck_assignments_target')),
    sa.CheckConstraint("target_type IN ('all', 'group', 'device')", name=op.f('ck_assignments_target_type')),
    sa.CheckConstraint('end_at IS NULL OR end_at > start_at', name=op.f('ck_assignments_period')),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name=op.f('fk_assignments_video_id_videos'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assignments'))
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_email', sa.String(length=254), nullable=True),
    sa.Column('user_name', sa.String(length=200), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('device_code', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_audit_log_device_id_devices'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_device_code'), ['device_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_user_email'), ['user_email'], unique=False)

    op.create_table('device_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=10), nullable=False),
    sa.Column('remote_name', sa.String(length=1000), nullable=False),
    sa.Column('is_dir', sa.Boolean(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('remote_mtime', sa.DateTime(), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('issues', sa.JSON(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('delete_requested_by', sa.String(length=254), nullable=True),
    sa.Column('delete_requested_at', sa.DateTime(), nullable=True),
    sa.Column('adopted_video_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['adopted_video_id'], ['videos.id'], name=op.f('fk_device_files_adopted_video_id_videos'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_device_files_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name=op.f('fk_device_files_video_id_videos'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_files')),
    sa.UniqueConstraint('device_id', 'location', 'remote_name', name=op.f('uq_device_files_device_id'))
    )
    op.create_table('device_groups',
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_device_groups_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_device_groups_group_id_groups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('device_id', 'group_id', name=op.f('pk_device_groups'))
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('message', sa.String(length=300), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=254), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('not_before', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('worker_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_jobs_device_id_devices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name=op.f('fk_jobs_video_id_videos'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_type'), ['type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_type'))
        batch_op.drop_index(batch_op.f('ix_jobs_status'))

    op.drop_table('jobs')
    op.drop_table('device_groups')
    op.drop_table('device_files')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_user_email'))
        batch_op.drop_index(batch_op.f('ix_audit_log_device_code'))
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    op.drop_table('assignments')
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_videos_sha256'))

    op.drop_table('videos')
    op.drop_table('users')
    op.drop_table('system_state')
    op.drop_table('groups')
    op.drop_table('devices')
    # ### end Alembic commands ###
